### ISSUE TITLE
Do not unassign users that have activity on a pull-request

### ISSUE THREAD

**Issue by gentlementlegen** [ubiquity-os-marketplace/daemon-disqualifier#21] opened 2024-09-13 06:08 UTC
I think there is an issue with the unassign. It doesn't seem to take into account linked pull-request activity, I got unassigned but opened my PR 12 hours ago. @0x4007 @Keyrxng rfc

_Originally posted by @gentlementlegen in https://github.com/ubiquibot/conversation-rewards/issues/82#issuecomment-2348092427_
            

Users that opened and linked a pull-request seem to be unassigned regardless of their activity. This should be taken into account before unassigning users.

Another example: https://github.com/ubiquity/ubiquity-dollar/issues/563#issuecomment-2350163159

**Comment by 0x4007** [comment] 2024-09-13 06:49
I am skeptical that this should be funded, because this just means that the original implementation was not done correctly. The person who implemented it originally should be responsible to handle this. They can lift most of the logic from v1, aside from how we detect the linked pull is different now (just a GraphQL query needs to be adjusted.)

**Comment by Keyrxng** [comment] 2024-09-15 15:05
The issue is the rest api that is being hit is not ideal. Currently we are using `rest.issues.listEvents` which isn't as abundant as `rest.issues.listEventsForTimeline` which contains everything that we want: comments, reviews etc.

Looking at the difference in results between the two is drastic. One question I have is, should we consider a review from one of us as activity on the issue?

- user does their job and PR awaits review
- on the 3rd day a review is submitted
- Should the deadline be extended from that review since that is out of the contributor's control or should we only consider a user' activity?

**Comment by Keyrxng** [comment] 2024-09-15 15:09
I'll add the whitelist as part of this PR too

whitelist:

- `push`
- `pull_request.opened`
- `pull_request_review_comment.created`
- `pull_request.ready_for_review`
- `pull_request.review_requested`
- `issue_comment.created`

**Comment by Keyrxng** [comment] 2024-09-15 16:30
This is a `committed` event payload. Notice how you are referred to by your display name @gentlementlegen which when you try to use that with the `users.getByUsername` endpoint it actually returns @mentlegen. 

Because of this, the only way I can get your real username from this payload is to parse the custom github email. I'm sure that they are standardized so it's probably a safe option so long as the user' email is the default github one.

This may be encounter issues down the line but I'm not sure how else to deal with this at the moment. 


```json

  {
    "sha": "0a7576d65ea6845f771c9b2c26c39481743ee32c",
    "node_id": "C_kwDOLUK0B9oAKDBhNzU3NmQ2NWVhNjg0NWY3NzFjOWIyYzI2YzM5NDgxNzQzZWUzMmM",
    "url": "https://api.github.com/repos/ubiquibot/conversation-rewards/git/commits/0a7576d65ea6845f771c9b2c26c39481743ee32c",
    "html_url": "https://github.com/ubiquibot/conversation-rewards/commit/0a7576d65ea6845f771c9b2c26c39481743ee32c",
    "author": {
      "name": "Mentlegen",
      "email": "9807008+gentlementlegen@users.noreply.github.com",
      "date": "2024-09-13T15:47:10Z"
    },
    "committer": {
      "name": "Mentlegen",
      "email": "9807008+gentlementlegen@users.noreply.github.com",
      "date": "2024-09-13T15:47:10Z"
    },
    "tree": {
      "sha": "b5951a27f44b77dea078380234380f2d02ab6969",
      "url": "https://api.github.com/repos/ubiquibot/conversation-rewards/git/trees/b5951a27f44b77dea078380234380f2d02ab6969"
    },
    "message": "feat: skip minimized comments",
    "parents": [
      {
        "sha": "0799f372ae52310d0e35318ab3087e9fb8ab8f32",
        "url": "https://api.github.com/repos/ubiquibot/conversation-rewards/git/commits/0799f372ae52310d0e35318ab3087e9fb8ab8f32",
        "html_url": "https://github.com/ubiquibot/conversation-rewards/commit/0799f372ae52310d0e35318ab3087e9fb8ab8f32"
      }
    ],
    "verification": {
      "verified": false,
      "reason": "unsigned",
      "signature": null,
      "payload": null
    },
    "event": "committed"
  },
```

**Comment by 0x4007** [comment] 2024-09-15 17:28
No just keep it simple. Any commit on the pull will count as activity.

**Comment by Keyrxng** [comment] 2024-09-15 18:18
> No just keep it simple. Any commit on the pull will count as activity.

1. Someone other than the contributor may push.
2. We are using the entire timeline which could mean commits across PRs so we need to scope it to the assignee.
3. I haven't encountered a scenario yet where the email isn't the noreply format but I think it is possible it can change.

**Comment by 0x4007** [comment] 2024-09-15 18:33
1. It's fine
2. Check timestamp

**Comment by Keyrxng** [comment] 2024-09-15 18:37
Sorry but checking the timestamp wouldn't work in this case because if there are two pulls within 3.5 - 7 days of each other then the activity would be wrong. For example `pay.ubq.fi` just had a contributor open three PRs within a day or two for the same issue, if there was one other contributor in the mix in the last week it wouldn't be accurate for either.

**Comment by 0x4007** [comment] 2024-09-15 18:48
It worked fine in v1 bot. And I'm pretty sure it was as simple as checking any linked pull for any commits. Then the assignee gets extra time. 

You don't need to make it more complicated than it needs to be.

**Comment by Keyrxng** [comment] 2024-09-15 19:09
We already collect the linked pull request and issue timeline and merged actually I was mistaken but I will refactor the PR so that it counts any commit as activity

https://github.com/ubiquibot/user-activity-watcher/blob/3684bece96ef48f1765231fc1c79b99300e20572/src/helpers/get-assignee-activity.ts#L10-L30

**Closed** 2024-10-23 04:47 UTC
Labels: Time: <1 Hour, Priority: 4 (Urgent), Price: 100 USD
